server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://pulpapp_users_db:5433/pulpapp_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect